### ISSUE TITLE
[Admob] Project AdTest raised exception class 6.

### ISSUE THREAD

**Issue by ISeosiI** [DelphiWorlds/Playground#10]
Hello

Currently testing for iOS.

An error occurs while performing an example of admob.

The current system is iOS 15.5 / Delphi 11.1 update 1.

Error message when running the app.

Project AdTest raised exception class 6.

libc++abi NSException Process

Please check.

thank you.

**Comment by DelphiWorlds** [comment]
I'm not seeing any exception here. Can you please provide the steps? This is what I did:

1. Compile/run the *demo*
2. Tap each of the Banner, Interstitial and Reward buttons, and tap the close button when each ad appears for Interstitial and Reward

No errors

**Comment by ISeosiI** [comment]
I'll tell you how to proceed.

It's basically the same as what you said.

Android works fine.

Execution Environment:

iOS 15.5 and macOS Monterey(Intel) 12.3.1

Windows 10, Delphi 11.1 Update 1

The following error occurs when running:

![1](https://user-images.githubusercontent.com/99629009/176087327-40773c1f-309a-40a0-86b1-47c0c5357b16.PNG)

![2](https://user-images.githubusercontent.com/99629009/176087339-e112b750-0c02-4528-b67f-3f1e90aab91c.PNG)

After debugging, DW.iOSapi.Google MobileAdunit fails.

The location is as follows.

![3](https://user-images.githubusercontent.com/99629009/176087370-8675ed3a-ea1d-4d9e-ab2c-e19667e34eed.PNG)

If you remove the source like this, it will run.

![4](https://user-images.githubusercontent.com/99629009/176087392-c8735314-3794-471e-a2ba-d1ff2cc665b8.jpg)

However, the following error occurs when running the advertisement.

![5](https://user-images.githubusercontent.com/99629009/176087422-2534a54d-20db-47ce-bfc8-641ac1138be4.PNG)

Please check.

thank you.

**Comment by DelphiWorlds** [comment]
> Please check.

I did check - the demo works for me, with _no_ alterations to the code. Please re-download the **current** source, and try it again. Also ensure you have the **current** source for Kastri, as this project is dependent on it

**Comment by ISeosiI** [comment]
1.

https://github.com/DelphiWorlds/Kastri

2. 
https://github.com/DelphiWorlds/Playground

All new, but the same error occurs.

![1](https://user-images.githubusercontent.com/99629009/176089249-a9d2b1b3-d04d-4ab0-9823-3bd1d8245349.PNG)
![2](https://user-images.githubusercontent.com/99629009/176089247-1ac4bc3f-a70d-4590-a2b7-1d64f2873440.PNG)

**Comment by ISeosiI** [comment]
Is there any way I can test it additionally?

**Comment by DelphiWorlds** [comment]
A fresh download is failing for me, too.. which is odd, because there aren't any changes pending. I'm looking into it.

**Comment by MyBuzzTechnologies** [comment]
Maybe an obvious question but have you included the skAdNetwork and other necessary entries to the info.plist file? If not that can cause an exception.
Check the Console app on the Mac connected to your phone as the iPhone console log may report the actual error associated with that crash.

**Comment by DelphiWorlds** [comment]
One of the newer Google Mobile Ads libraries was not included in the last push, however on my machine I had the new version and git was not showing that they were different. Please update at least the Lib\iOS\UserMessagingPlatform.framework folder from the demo, and it should now work

**Comment by ISeosiI** [comment]
> 
There is no part added to info.plist because the demo is currently running.
Do I have to add it separately?

**Comment by ISeosiI** [comment]
> One of the newer Google Mobile Ads libraries was not included in the last push, however on my machine I had the new version and git was not showing that they were different. Please update at least the Lib\iOS\UserMessagingPlatform.framework folder from the demo, and it should now work

I received it through cocoapod from mac.

However, it does not work.
![image](https://user-images.githubusercontent.com/99629009/176112928-ed054ced-7ea3-4973-881c-56e0baa49998.png)

**Comment by DelphiWorlds** [comment]
> There is no part added to info.plist because the demo is currently running.

I didn't have to update the info.plist.

> I received it through cocoapod from mac.

Use the one from the demo, because it is compatible with the demo code

**Comment by ISeosiI** [comment]
I got a new one from git, but it doesn't work.

Is there a solution?

**Comment by DelphiWorlds** [comment]
Sorry.. Chris was right about the info.plist file. I've now pushed the required file (in the root of the demo)

**Comment by ISeosiI** [comment]
It works fine.

Thank you for your support.
