### ISSUE TITLE
FCMRebooted?

### ISSUE THREAD

**Issue by alissonrodrigo** [DelphiWorlds/Playground#12]
I use Kastri to manage notifications (https://github.com/DelphiWorlds/Kastri/tree/master/Demos/FirebaseCloudMessaging), would you advise me to switch to FCRMRebooted?
Looking at the documentation it seems to contain less code

**Comment by DelphiWorlds** [comment]
For some weird reason, I haven't noticed this issue til now. I suggest you at least try FCMRebooted. I had a project for a client where very similar code was put into production, and I plan on adding this to Kastri, soon
