### ISSUE TITLE
[Biometric] Version 64-bits

### ISSUE THREAD

**Issue by edsonalanis** [DelphiWorlds/Playground#13]
These steps only work for 32-bit Android, how to do the same for 64-bit which is the version we posted on Google Play?

**Comment by DelphiWorlds** [comment]
I updated the [readme](https://github.com/DelphiWorlds/Playground/blob/main/Demos/Biometric/ReadMe.md) as to how to build for 64-bit

**Comment by edsonalanis** [comment]
OK, is there an easy way to add the files to Delpoy that need to be added? on Android 32-bit there are several files that I need to include for Android 64-bit

**Comment by DelphiWorlds** [comment]
For now, you could use [DeployMan](https://github.com/grijjy/GrijjyDeployMan/releases/tag/v1.1) from Grijjy. I'm working on a new version of [Codex](https://github.com/DelphiWorlds/Codex) that will allow you to easily deploy complete folders right from the IDE.
