### ISSUE TITLE
swipe, slides...

### ISSUE THREAD

**Issue by alissonrodrigo** [DelphiWorlds/Playground#14]
I took a look at the Swipe code but I couldn't make it "dynamic" ie put as many slides as needed, 1 or 3 to 5. how many slides are needed

**Comment by DelphiWorlds** [comment]
You don't add more "slides" - it only ever has 3. I'll be expanding the demo to show how to manage this

**Comment by DelphiWorlds** [comment]
I've now expanded the demo to illustrate its use, i.e. that there are only 3 "slides" - they are populated with the relevant content when a user swipes from one to the next
