### ISSUE TITLE
[Biometric] Unexpected firing of SuccessResultMethod and FailResultMethod on Android 13

### ISSUE THREAD

**Issue by rj1102** [DelphiWorlds/Playground#16]
I have tested the biometric demo project on my old Android 9 device (Huawei P20 Lite) and it worked well, i.e. no crash and both SuccessResultMethod and FailResultMethod are fired as expected.
I also have tested it on my Android 13 device (Oppo A74) but here I have some issues regarding unexpected firing of the SuccessResultMethod and FailResultMethod.
Shall I report these issues or is the Playground Biometric demo still work in progress for higher Android versions?

(Using Delphi 11.2/Windows)

**Comment by DelphiWorlds** [comment]
> Shall I report these issues or is the Playground Biometric demo still work in progress for higher Android versions?

This report will be sufficient, thanks!

**Comment by DelphiWorlds** [comment]
Closed as per: https://github.com/DelphiWorlds/Kastri/issues/151#issuecomment-1410750970
