### ISSUE TITLE
Swipe

### ISSUE THREAD

**Issue by alissonrodrigo** [DelphiWorlds/Playground#19]
Is there any possibility to make the “slides” dynamic? if I study the library is it possible to do this, put 2 or even more scenes like 6?

**Comment by DelphiWorlds** [comment]
Please read the readme again, i.e.:

"This is achieved by parenting controls to the Left, Center and Right layouts (see the demo code as to how). When a user swipes left or right, the controls simply swap around. Controls can be re-populated in the OnSwiped event e.g. if the user has swiped left, the control parented to the right hand layout could have its content changed, and the same for the left hand layout for when the user swipes right."

and examine the demo code again.  There is no need for any more than 3.
