### ISSUE TITLE
VKObserver doesn't reset the top margin back to original value

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [DelphiWorlds/Playground#20]
The VKObserver works really well. I've tested it with various scenarios, including when the edit box and memo box are inside a TListBox control (as I do in a lot of my UI).

There are 2 issues which I'll raise as separate tickets.

If the container control already has a top margin set, this is reset to 0 when the control loses focus as the code doesn't capture the original value.

**Comment by DelphiWorlds** [comment]
Pushed a change that should fix this

**Comment by MyBuzzTechnologies** [comment]
Thanks!
