### ISSUE TITLE
ExoPlayerDemo Error

### ISSUE THREAD

**Issue by jiangwei7480** [DelphiWorlds/Playground#23]
hi,hello:
  when I run ExoPlayer Demo,Happen error.
  
![image](https://github.com/DelphiWorlds/Playground/assets/80150274/dee7ea0e-bdd0-4629-8903-426c4f318d35)

I don't do with it.Please you check and edit it. Thank you.
Develpor Env: D12.1

**Comment by DelphiWorlds** [comment]
I am not seeing this error, also using Delphi 12.1. Are you building the demo, or your own project? If it is the demo, have you made any changes to the demo files?

Also, there is a [new demo in the Kastri repo](https://github.com/DelphiWorlds/Kastri/tree/master/Demos/VideoPlayer), which replaces this project.
