### ISSUE TITLE
Usssd Demo Jar file missing some fix !

### ISSUE THREAD

**Issue by mben-dz** [DelphiWorlds/Playground#24]
Project kastri.apk raised exception class EJNI with message 'Java type JDWUssdResponseCallback could not be found'.
--
i rename package demo to this:
com.delphiworlds.kastri
according to the java files :
```
package com.delphiworlds.kastri;

import android.telephony.TelephonyManager;

public class DWUssdResponseCallback extends TelephonyManager.UssdResponseCallback {

  private DWUssdResponseCallbackDelegate mDelegate;

  public DWUssdResponseCallback(DWUssdResponseCallbackDelegate delegate) {
    mDelegate = delegate;
  }

  @Override
  public void onReceiveUssdResponse(TelephonyManager telephonyManager, String request, CharSequence response) {
    mDelegate.onReceiveUssdResponse(telephonyManager, request, response);
  }

  @Override
  public void onReceiveUssdResponseFailed(TelephonyManager telephonyManager, String request, int failureCode) {
    mDelegate.onReceiveUssdResponseFailed(telephonyManager, request, failureCode);
  }
}
```
--
```
package com.delphiworlds.kastri;

import android.telephony.TelephonyManager;

public interface DWUssdResponseCallbackDelegate {

  public void onReceiveUssdResponse(TelephonyManager telephonyManager, String request, CharSequence response);

  public void onReceiveUssdResponseFailed(TelephonyManager telephonyManager, String request, int failureCode);
}
```
---
how to fix this ?

**Comment by DelphiWorlds** [comment]
You need to add [dw-telephony.jar](https://github.com/DelphiWorlds/Playground/blob/main/Lib/dw-telephony.jar) to the Android 32-bit target, as per the demo project

**Comment by mben-dz** [comment]
Check out my repository here:
[JarBuilder](https://github.com/mben-dz/JarBuilder)

I developed JarBuilder as a tool to create a custom UssdLib.jar instead of using dw-telephony.jar. This allows me to generate the JAR file tailored to my application's package name
--
i always get that error above!!
--
does the java files works only on Android 32 bit ?

**Comment by DelphiWorlds** [comment]
> does the java files works only on Android 32 bit ?

Adding it to the 32-bit target just means that the .jar will be compiled for 32-bit and/or 64-bit.

> i always get that error above!!

Are you actually adding it to the project?

**Comment by mben-dz** [comment]
yes i add it successfully
my phone is android 5.1 (21 Api) 
my delphi is Athens  first build version

**Comment by DelphiWorlds** [comment]
Are you using the same source files? Can you attach UssdLib.jar here?

**Comment by mben-dz** [comment]
https://github.com/mben-dz/JarBuilder/blob/main/Tested.rar

**Comment by DelphiWorlds** [comment]
You are receiving the message `Java type JDWUssdResponseCallback could not be found` because you have used your own class names in your sources. You will need to change the imports in [this unit](https://github.com/DelphiWorlds/Playground/blob/main/API/DW.Androidapi.JNI.DWTelephony.pas) to match your Java source.

**Comment by DelphiWorlds** [comment]
You will also need to modify the source in [this unit](https://github.com/DelphiWorlds/Playground/blob/main/Features/Telephony/DW.UssdRequester.pas). Leaving everything as it was would have been much easier, and would also indicate the code came from me.

**Comment by mben-dz** [comment]
i do all of that before and still no chance, even with the default demo i have same issue,
i try to test the jar [dw-telephony.jar](https://github.com/DelphiWorlds/Playground/blob/main/Lib/dw-telephony.jar) with Java2OP.exe and he tell me this:
```
android.telephony.TelephonyManager$UssdResponseCallback: not found
 com.delphiworlds.kastri.DWUssdResponseCallback: the parent class (android.telephony.TelephonyManager$UssdResponseCallback) is not found
```
I believe the issue isn't on my end.

**Comment by DelphiWorlds** [comment]
[This is the class](https://developer.android.com/reference/android/telephony/TelephonyManager.UssdResponseCallback), available from API level 26 (Android 8). If Java2OP is using `android.jar` from API 26 or higher and has that error, then Java2OP is broken. Also, the error from your first post indicates that the class is not being included when the project is built, so it is more likely that it just has not been added to the project correctly

**Comment by DelphiWorlds** [comment]
Is this still an issue?

**Comment by mben-dz** [comment]
Yes, the TelephonyManager.sendUssdRequest function only works on Android API Level 26 and above. Initially, I was developing my own custom solution without embedding any external JAR files. However, since my phone is running Android 5.1, I had to abandon the project because the sendUssdRequest function is unsupported. I also noticed that on newer devices, apps using this function often experience slow response times.

To address this issue, I explored another solution: embedding NDK files into the project. By using the Android Native Development Kit (NDK), I was able to interact directly with the Radio Interface Layer (RIL), which operates at a lower system level. This allowed me to request USSD responses efficiently without needing root access.

For example, you can create a simple NDK module that communicates with the RIL. Here's a brief outline of how it might look:

1) Create an NDK C++ file that interacts with RIL:
`extern "C" JNIEXPORT jstring JNICALL
Java_com_example_ussd_RilRequest_getUssdResponse(JNIEnv* env, jobject /* this */, jstring ussdCode) {
    // Interact with RIL here to send the USSD code and receive the response.
    // Return the USSD response as a string.
}
`
--
2) Compile the NDK files into a shared library (.so file) and include it in your Android project.

3) In your Android app, call the native method from Java:
`public class RilRequest {
    static {
        System.loadLibrary("ril-ndk");
    }

    public native String getUssdResponse(String ussdCode);
}

// Example usage
String response = new RilRequest().getUssdResponse("*123#");
`
--
By using this approach, you bypass the limitations of sendUssdRequest on older Android versions and achieve faster results, all while keeping your app lightweight without the need for external JARs.

**Comment by mben-dz** [comment]
Yes, the **TelephonyManager.sendUssdRequest** function only works on **Android API Level 26** and above. Initially, I was developing my own custom solution without embedding any external JAR files. However, since my phone is running Android 5.1, I had to abandon the project because the sendUssdRequest function is unsupported. I also noticed that on newer devices, apps using this function often experience slow response times.

To address this issue, I explored another solution: **embedding NDK** files into the project. By using the **Android Native Development Kit (NDK)**, I think to interact directly with the Radio Interface Layer (RIL), which operates at a lower system level is not impossible. This allowed us to request USSD responses efficiently without needing root access.

For example, you can create a simple NDK module that communicates with the RIL. Here's a brief outline of how it might look:

1) Create an NDK C++ file that interacts with RIL:
`extern "C" JNIEXPORT jstring JNICALL
Java_com_example_ussd_RilRequest_getUssdResponse(JNIEnv* env, jobject /* this */, jstring ussdCode) {
    // Interact with RIL here to send the USSD code and receive the response.
    // Return the USSD response as a string.
}
`
--
2) Compile the NDK files into a shared library (.so file) and include it in your Android project.

3) In your Android app, call the native method from Java:
`public class RilRequest {
    static {
        System.loadLibrary("ril-ndk");
    }

    public native String getUssdResponse(String ussdCode);
}

// Example usage
String response = new RilRequest().getUssdResponse("*123#");
`
--
By using this approach, you bypass the limitations of sendUssdRequest on older Android versions and achieve faster results, all while keeping your app lightweight without the need for external JARs.
--
my solution not complete yet ..!!

**Comment by mben-dz** [comment]
Yes, the **TelephonyManager.sendUssdRequest** function only works on **Android API Level 26** and above. Initially, I was developing my own custom solution without embedding any external JAR files. However, since my phone is running Android 5.1, I had to abandon the project because the sendUssdRequest function is unsupported. I also noticed that on newer devices, apps using this function often experience slow response times.

To address this issue, I explored another solution: **embedding NDK** files into the project. By using the **Android Native Development Kit (NDK)**, I think to interact directly with the Radio Interface Layer (RIL), which operates at a lower system level is not impossible. This allowed us to request USSD responses efficiently without needing root access.

For example, you can create a simple NDK module that communicates with the RIL. Here's a brief outline of how it might look:

1) Create an NDK C++ file that interacts with RIL:
`extern "C" JNIEXPORT jstring JNICALL
Java_com_example_ussd_RilRequest_getUssdResponse(JNIEnv* env, jobject /* this */, jstring ussdCode) {
    // Interact with RIL here to send the USSD code and receive the response.
    // Return the USSD response as a string.
}
`
--
2) Compile the NDK files into a shared library (.so file) and include it in your Android project.

3) In your Android app, call the native method from Java:
`public class RilRequest {
    static {
        System.loadLibrary("ril-ndk");
    }

    public native String getUssdResponse(String ussdCode);
}

// Example usage
String response = new RilRequest().getUssdResponse("*123#");
`
--
By using this approach, you bypass the limitations of sendUssdRequest on older Android versions and achieve faster results, all while keeping your app lightweight.
--
my solution not complete yet ..!!

**Comment by DelphiWorlds** [comment]
> my solution not complete yet ..!!

What error messages are there, if any?

**Comment by mben-dz** [comment]
https://github.com/mben-dz/MyVideos/blob/main/UssdKastri.mp4

**Comment by DelphiWorlds** [comment]
As per my earlier comment:

> You need to add [dw-telephony.jar](https://github.com/DelphiWorlds/Playground/blob/main/Lib/dw-telephony.jar) to the Android 32-bit target, as per the demo project

Note **Android 32-bit target.** Adding it there it will compile for both 32-bit and 64-bit

**Comment by mben-dz** [comment]
https://chatgpt.com/share/66f87dce-6398-8005-8c03-a93c7d10b2ee

**Comment by DelphiWorlds** [comment]
Can you provide some explanation of what the link is for?

**Comment by mben-dz** [comment]
I’ve embedded the JAR file correctly and ensured that the delegate function is implemented, but unfortunately, the delegate still doesn't work on my phone running Android 5.1. After some investigation, I found that this might be due to the fact that the delegate is not being properly registered or supported on this version of Android.

Even though the Java code is correct and should work on more recent Android versions, it appears that Android 5.1 has some limitations or differences in the way it handles TelephonyManager callbacks, which prevents the delegate from functioning as expected.

For this reason, I had to fall back to using native JNI methods to handle the USSD responses, which is more reliable across different Android versions.

**Comment by DelphiWorlds** [comment]
> For this reason, I had to fall back to using native JNI methods to handle the USSD responses, which is more reliable across different Android versions.

OK - did you manage to get this working?

**Comment by mben-dz** [comment]
Not yet, I'll share my solution once I'm certain it's working properly.

**Comment by mben-dz** [comment]
Here is what I've recently reached regarding the topic of Java Code Native:
--
NativeUssdResponseCallback.java
--
`

	package com.MBenDelphi.NativeUssdDemo;

	import android.telephony.TelephonyManager;
	import android.os.Handler;
	import android.os.Looper;

	public class NativeUssdResponseCallback extends TelephonyManager.UssdResponseCallback {

		private Handler callbackHandler;

		// Constructor with the handler parameter
		public NativeUssdResponseCallback() {
			this.callbackHandler = new Handler(Looper.getMainLooper());
		}

		// Public method to retrieve the handler
		public Handler getMainLooperHandler() {
			return this.callbackHandler;
		}

		@Override
		public void onReceiveUssdResponse(TelephonyManager telephonyManager, String request, CharSequence response) {
			callbackHandler.post(() -> {
				nativeOnReceiveUssdResponse(request, response.toString());
			});
		}

		@Override
		public void onReceiveUssdResponseFailed(TelephonyManager telephonyManager, String request, int failureCode) {
			callbackHandler.post(() -> {
				nativeOnReceiveUssdResponseFailed(request, failureCode);
			});
		}

		// Declare native methods that will be implemented in Delphi
		public native void nativeOnReceiveUssdResponse(String aRequest, String aResponse);
		public native void nativeOnReceiveUssdResponseFailed(String aRequest, int aFailureCode);
	}

`
---
NativeUssdHandler.java
---
`

	package com.MBenDelphi.NativeUssdDemo;

	import android.telephony.TelephonyManager;
	import android.os.Handler;

	public class NativeUssdHandler {

		private TelephonyManager delphiTelephonyMgr;

		public NativeUssdHandler(TelephonyManager aTelephonyMgr) {
			this.delphiTelephonyMgr = aTelephonyMgr;
		}

		// Method to send a USSD request, taking NativeUssdResponseCallback as a parameter
		public void sendUssdRequest(String aUssdCode, NativeUssdResponseCallback aUssdCallback) {
			delphiTelephonyMgr.sendUssdRequest(aUssdCode, aUssdCallback, aUssdCallback.getMainLooperHandler());
		}
	}
`
--
The last class will need some minor adjustments to fully adapt to all phones. Currently, it uses the sendUssdRequest code, which doesn't work on phones with Android versions lower than 8.

I hope you like the idea initially.

**Comment by mben-dz** [comment]
`  
	  Androidapi.JNI.NativeUssdCall;  // Include the JNI binding for NativeUssdHandler

	type
	  TUssdHandler = class//(TJavaLocal, JNativeUssdHandler)
	  strict private
		[weak] // Use weak references to prevent memory leaks
		fTelephonyManager: JTelephonyManager;
		[weak] // Use weak references to prevent memory leaks
		fNativeUssdHandler: JNativeUssdHandler;
		[weak] // Use weak references to prevent memory leaks
		fNativeUssdResponseCallback: JNativeUssdResponseCallback;

		procedure UnregisterNativeUssdJNI; inline;
		procedure RegisterNativeMethods; inline;
		procedure InitUssdHandler; inline; // Marked as inline for potential performance gain
	  private
		procedure nativeOnReceiveUssdResponse(aRequest: JString; aResponse: JString); cdecl;
		procedure nativeOnReceiveUssdResponseFailed(aRequest: JString; aFailureCode: Integer); cdecl;
	  protected
		constructor Create(aTelephonyMgr: JTelephonyManager); overload; virtual; // Constructor to initialize the TelephonyManager

	  public
		class function Wrap: TUssdHandler; overload;
		destructor Destroy; override;

		procedure Send_UssdRequest(aUssdCode: String);
	  end;

	implementation

	uses
	  FMX.Dialogs;

	function GetTelephonyManager: JTelephonyManager;
	begin
	  Result := TJTelephonyManager.Wrap(
		(TAndroidHelper.Context
		   .getSystemService(TJContext.JavaClass.TELEPHONY_SERVICE) as ILocalObject).GetObjectID);
	end;

	{ TUssdHandler }

	procedure TUssdHandler.InitUssdHandler;
	begin
	  // Initialize the Java NativeUssdResponseCallback..
	  fNativeUssdResponseCallback :=
		TJNativeUssdResponseCallback.JavaClass.init;

	  // Initialize the Java NativeUssdHandler with the Delphi fTelephonyManager
	  fNativeUssdHandler := TJNativeUssdHandler.JavaClass.init(fTelephonyManager);
	  RegisterNativeMethods; // register the native methods ..

	end;

	// This method registers the native methods with the Java class
	procedure TUssdHandler.RegisterNativeMethods;
	var
	  LMethods: array[0..1] of JNINativeMethod;
	  LJNIEnv: PJNIEnv;
	  LJavaClassID: JNIClass;
	begin
	  LJNIEnv := TJNIResolver.GetJNIEnv;
	  LJavaClassID := TJNIResolver
		.GetJavaClassID('com/MBenDelphi/NativeUssdDemo/NativeUssdResponseCallback');

	  // Set up native method array for registration
	  LMethods[0].Name := 'nativeOnReceiveUssdResponse';
	  LMethods[0].Signature := '(Ljava/lang/String;Ljava/lang/String;)V';
	  LMethods[0].FnPtr := @TUssdHandler.nativeOnReceiveUssdResponse;

	  LMethods[1].Name := 'nativeOnReceiveUssdResponseFailed';
	  LMethods[1].Signature := '(Ljava/lang/String;I)V';
	  LMethods[1].FnPtr := @TUssdHandler.nativeOnReceiveUssdResponseFailed;

	  // Register the native LMethods with the JVM
	  if LJNIEnv^.RegisterNatives(LJNIEnv, LJavaClassID,
		  PJNINativeMethod(@LMethods[0]), Length(LMethods)) < 0 then
	  begin
		raise Exception.Create('Failed to register native methods');
	  end;
	end;

	procedure TUssdHandler.UnregisterNativeUssdJNI;
	var
	  LJNIEnv: PJNIEnv;
	  LJavaClassID: JNIClass;
	begin
	  // Obtain the JNI environment
	  LJNIEnv := TJNIResolver.GetJNIEnv;

	  // Retrieve the Java class where the native methods were registered
	  LJavaClassID := TJNIResolver
		.GetJavaClassID('com/MBenDelphi/NativeUssdDemo/NativeUssdResponseCallback');

	  // Unregister the native methods
	  if LJNIEnv^.UnregisterNatives(LJNIEnv, LJavaClassID) < 0 then
	  begin
		raise Exception.Create('Failed to unregister native methods');
	  end;
	end;

	constructor TUssdHandler.Create(aTelephonyMgr: JTelephonyManager);
	begin inherited Create;

	  // Assign the provided TelephonyManager to the class variable
	  fTelephonyManager := aTelephonyMgr; // Use the passed TelephonyManager
	  InitUssdHandler; // Initialize the Java handler
	end;

	class function TUssdHandler.Wrap: TUssdHandler;
	begin
	  // Call GetTelephonyManager to get the current TelephonyManager instance
	  Result := Self.Create(GetTelephonyManager);
	end;

	destructor TUssdHandler.Destroy;
	begin
	  UnregisterNativeUssdJNI;

	  inherited;
	end;

	procedure TUssdHandler.NativeOnReceiveUssdResponse(aRequest, aResponse: JString);
	begin
	  // Handle the received USSD response
	  ShowMessage(JStringToString(aResponse)); // Display the response in a message box
	end;

	procedure TUssdHandler.NativeOnReceiveUssdResponseFailed(aRequest: JString; aFailureCode: Integer);
	begin
	  // Handle the failed USSD response
	  ShowMessage(Format('USSD request failed. Code: %d', [aFailureCode])); // Display failure message
	end;

	procedure TUssdHandler.Send_UssdRequest(aUssdCode: String);
	begin
	  // Call the Java method to send the USSD request
	  if Assigned(fNativeUssdHandler) then
		fNativeUssdHandler.sendUssdRequest(StringToJString(aUssdCode), fNativeUssdResponseCallback);
	end;

	end.
`

**Comment by mben-dz** [comment]
the updated Java files are [here](https://github.com/mben-dz/MBenDelphi-Native-Ussd-Handler)
--
I’ll post the complete demo as soon as it’s finished and working properly

**Comment by DelphiWorlds** [comment]
Excellent, thanks!

**Comment by mben-dz** [comment]
I've finally succeeded in getting the native methods to work exactly as I expected!
the complete demo is [here](https://github.com/mben-dz/NativeJavaMethodsCall).
