### ISSUE TITLE
TestMode

### ISSUE THREAD

**Issue by bilal21dz** [DelphiWorlds/Playground#3]
Please implement TestMode: = False

**Comment by okbach** [comment]
I noticed a strange thing that seems to be affected by the banner when I activate the test mode
Interstitial ads also become in test . mode

**Comment by DelphiWorlds** [comment]
I'm assuming you mean in the Advertising feature? I'm not setting anything called TestMode to True - the demo just uses a test id (i.e. `ca-app-pub-3940256099942544/1033173712`) for the AdUnitId

**Comment by DelphiWorlds** [comment]
I note from the built-in advertising code, that if you set TestMode on a banner ad that it makes a call to

`TJMobileAds.JavaClass.setRequestConfiguration`

So test mode appears to be something that is application-wide i.e. you cannot turn it on/off for different ad types

**Comment by DelphiWorlds** [comment]
This is the documentation regarding testing: https://developers.google.com/admob/android/test-ads

If this is what you are referring to, it is indeed application-wide.

**Comment by bilal21dz** [comment]
Ok, thank you👍
