### ISSUE TITLE
admob component 

### ISSUE THREAD

**Issue by bilal21dz** [DelphiWorlds/Playground#5]
[dcc32 Fatal Error] DW.AdMobBannerAd.pas(14): F1026 File not found: 'DW.GlobalDefines.inc'

**Comment by DelphiWorlds** [comment]
Please read the instructions in the readme, regarding Project Configuration: https://github.com/DelphiWorlds/Playground/blob/main/Readme.md

**Comment by DelphiWorlds** [comment]
Is your issue solved?

**Comment by bilal21dz** [comment]
Yes, thanks
