### ISSUE TITLE
TInterstitialAd displays reward ads.

### ISSUE THREAD

**Issue by kabiri** [DelphiWorlds/Playground#6]
TInterstitialAd displays reward ads.
Only a routine should be added to notify the program if a reward is received

**Comment by DelphiWorlds** [comment]
> TInterstitialAd displays reward ads.

If that's the case, blame Google. The code uses the correct classes.

> Only a routine should be added to notify the program if a reward is received

I am not sure what you mean here. Only the rewarded types of classes (e.g. `TRewardedAd`) have a notification when receiving a reward

**Comment by DelphiWorlds** [comment]
This is a screenshot of the ad shown when using `TInterstitialAd`, with a test AdUnitId:

![image](https://user-images.githubusercontent.com/22670829/152657925-f1cda5ab-409d-46bb-9240-a672e66752f5.png)

**Comment by kabiri** [comment]
i know , it displays TInterstitialAd correctly.But it also displays TRewardedAd.
Google probably made a mistake
