### ISSUE TITLE
[adMob] Does it work with Delphi 11?

### ISSUE THREAD

**Issue by kabiri** [DelphiWorlds/Playground#7]
Does rewardAd work with Delphi 11?
i see only banerad demo

**Comment by DelphiWorlds** [comment]
Yes

**Comment by kabiri** [comment]
sorry i edit my question
Does rewardAd work with Delphi 11?
i see only banerad demo

**Comment by DelphiWorlds** [comment]
The demo in its current form literally demos TRewardedAd. There is an installable component only for TAdMobBannerAd, since all the others are full screen

**Comment by kabiri** [comment]
Thank you
I looked at the source, you brought all the models in one demo

**Comment by kabiri** [comment]
Only in the Android demo you did not deactivate the libraries you mentioned.

**Comment by DelphiWorlds** [comment]
The libraries do not need to be deactivated in Delphi 11, just in Delphi 10.4, as per the readme
